#!/bin/sh

#
# This script computes the various flags needed to run GNU C++ testsuites
# (compiler specific as well as library specific). 
#
# Written by Benjamin Kosnik <bkoz@redhat.com>
#            Gabriel Dos Reis <gdr@codesourcery.com>
#

# Print a message saying how this script is intended to be invoked
print_usage() {
    cat <<EOF
Usage: 
    testsuite_flags --install-includes
		    --build-includes
		    --build-cxx
		    --install-cxx
		    --cxxflags
		    --cxxpchflags
EOF
}

# Establish configure-generated directory structure.
BUILD_DIR=/toolchain/openrsdk/rsdk-1.3.6/stage/1.3.6/uclibc/gcc-3.4.6-step2/mips-linux/libstdc++-v3
SRC_DIR=/toolchain/openrsdk/rsdk-1.3.6/gcc-3.4.6/libstdc++-v3
PREFIX_DIR=/toolchain/openrsdk/rsdk-1.3.6/release/rsdk-1.3.6/linux/uclibc
query=$1

case ${query} in
    --install-includes)
      INCLUDES="-I${SRC_DIR}/testsuite"
      echo ${INCLUDES}
      ;;
    --build-includes)
      INCLUDES="-nostdinc++ -I/toolchain/openrsdk/rsdk-1.3.6/stage/1.3.6/uclibc/gcc-3.4.6-step2/mips-linux/libstdc++-v3/include/mips-linux -I/toolchain/openrsdk/rsdk-1.3.6/stage/1.3.6/uclibc/gcc-3.4.6-step2/mips-linux/libstdc++-v3/include -I/toolchain/openrsdk/rsdk-1.3.6/gcc-3.4.6/libstdc++-v3/libsupc++ -I${SRC_DIR}/libsupc++ 
                -I${SRC_DIR}/include/backward -I${SRC_DIR}/testsuite"
      echo ${INCLUDES}
      ;;
    --install-cxx)
      CXX=${PREFIX_DIR}/bin/g++
      echo ${CXX}
      ;;
    --build-cxx)
      CXX_build=" /toolchain/openrsdk/rsdk-1.3.6/stage/1.3.6/uclibc/gcc-3.4.6-step2/gcc/xgcc -shared-libgcc -B/toolchain/openrsdk/rsdk-1.3.6/stage/1.3.6/uclibc/gcc-3.4.6-step2/gcc/ -nostdinc++ -L/toolchain/openrsdk/rsdk-1.3.6/stage/1.3.6/uclibc/gcc-3.4.6-step2/mips-linux/libstdc++-v3/src -L/toolchain/openrsdk/rsdk-1.3.6/stage/1.3.6/uclibc/gcc-3.4.6-step2/mips-linux/libstdc++-v3/src/.libs -B/toolchain/openrsdk/rsdk-1.3.6/release/rsdk-1.3.6/linux/uclibc/mips-linux/bin/ -B/toolchain/openrsdk/rsdk-1.3.6/release/rsdk-1.3.6/linux/uclibc/mips-linux/lib/ -isystem /toolchain/openrsdk/rsdk-1.3.6/release/rsdk-1.3.6/linux/uclibc/mips-linux/include -isystem /toolchain/openrsdk/rsdk-1.3.6/release/rsdk-1.3.6/linux/uclibc/mips-linux/sys-include"
      CXX=`echo "$CXX_build" | sed 's,gcc/xgcc ,gcc/g++ ,'`
      echo ${CXX}
      ;;
    --cxxflags)
      CXXFLAGS_save="-g -O2 -D_GLIBCXX_ASSERT"
      CXXFLAGS_config='-ffunction-sections -fdata-sections  -fmessage-length=0 
 		       -DLOCALEDIR="/toolchain/openrsdk/rsdk-1.3.6/stage/1.3.6/uclibc/gcc-3.4.6-step2/mips-linux/libstdc++-v3/po/share/locale" '
      echo ${CXXFLAGS_save} ${CXXFLAGS_config}
      ;;
    --cxxpchflags)
      PCHFLAGS="-include bits/stdc++.h"
      echo ${PCHFLAGS}
      ;;
    *)
      print_usagex
      ;;
esac

exit 0
